---
bibliography: ["../bib/references.bib", "../bib/packages.bib"]
---

# Restricted mean Survival Time {#sec-rmst}

Next, we address the restricted mean survival time (RMST) as an alternative estimand for the hazard ratio as it is defined in (@eq-phr).
Mathematically, the RMST is the expectation of the transformation $f(T | t^*) = \min(T, t^*)$ of the random variable $T$ where $t^*$ is the restriction time that needs to be specified by the researcher.
The RMST can be interpreted as the expected survival time from the time origin $0$ up to the restriction time $t^*$ [@royston2011].
Using exemplary numbers @royston2011 provide a clinical interpretation of the RMST:
"[Y]our life expectancy with X treatment and Z disease over the next 18 months is 9 months".
Moreover, considering a two-sample comparison based on the RMST difference, they further extend this interpretation [@royston2011]:
"[T]reatment A increases your life expectancy during the next 18 months by 2 months, compared with treatment B."
The RMST can be calculated by integrating the survival function from time $0$ to $t^*$ [@royston2011], i.e.
$$
\mu(t^*) = E[\min(T, t^*)] = \int_0^{t^*} S(u) \,du
\, .
$$ {#eq-rmst}
The reason for considering a restricted version of the mean is right-censoring of the survival data.
For the nonparametric Kaplan-Meier estimator of the survival function to reach $0$ and therefore being able to estimate an unrestricted mean, the largest event time needs to be uncensored, which is seldom the case.
On the other hand, employing parametric models in survival analysis is often a difficult task.
Even if we had a model with a decent in-sample fit, we cannot be sure whether the extrapolation of that model to the tail of the survival distribution is adequate [@royston2011].
Using the definition (@eq-rmst) of the RMST actual effect measures can be obtained by either considering ratios $\mu_1(t^*) / \mu_0(t^*)$ or differences $\mu_1(t^*) - \mu_0(t^*)$ of the RMST, e.g. between two groups [@uno2014].
The main advantage of using the RMST and group contrasts thereof in comparison to the prevalent hazard ratio is that it is a model free effect measure and has a clear clinical interpretation, though this might be subject to discussion [@freidlin2019].
To further enhance the understanding of the RMST @fig-rmst provides a visual demonstration of it based on survival functions of the exponential distribution.
The left panel depicts the situation for a single sample while the right panel illustrates the RMST difference as an effect measure.

```{r}
#| label: fig-rmst
#| fig-cap: "Illustration of the RMST: one-sample RMST (left) and two-sample RMST difference (right)"
#| fig-scap: "Illustration of the RMST"
#| fig-width: 10
#| fig-height: 5

# One sample plot ----

lambda0 = 0.2

dt = data.table(
  time = seq(0, 10.5, length.out = 250),
  surv = exp(- (lambda0 * seq(0, 10.5, length.out = 250)))
)

p1 = ggplot(dt, aes(time, surv)) +
  geom_line(color = "#E69F00", linewidth = 1.1) +
  geom_area(color = "#E69F00", fill = "#E69F00", alpha = 0.4, data = dt[time <= 10]) +
  # Indicator line for RMST cutoff
  geom_vline(
    xintercept = 10, linewidth = 0.9,
    linetype = "longdash", color = "#222222"
  ) +
  # Fine-tuning of axes
  scale_x_continuous(
    breaks = seq(0, 10, by = 2.5),
    limits = c(0, 10.5),
    expand = expansion(mult = c(0, 0), add = c(0.5, 0))
  ) +
  scale_y_continuous(limits = 0:1) +
  # Axes labels
  labs(x = "\nTime", y = "Survival probability\n")


# Two-sample plot ----

lambda0 = 0.2
lambda1 = 0.1

dt = data.table(time = seq(0, 10.5, length.out = 250))
dt[, `:=`(surv0 = exp(- (lambda0 * time)), surv1 = exp(- (lambda1 * time)))]

p2 = ggplot(dt) +
  geom_ribbon(
    aes(x = time, ymin = surv0, ymax = surv1), data = dt[time <= 10],
    color = "#999999", fill = "#999999", alpha = 0.5
  ) +
  geom_line(aes(time, surv0, color = "T0"), linewidth = 1.1) +
  geom_line(aes(time, surv1, color = "T1"), linewidth = 1.1) +
  scale_color_manual(
    name = NULL,
    values = c("T0" = "#E69F00", "T1" = "#56B4E9"),
    labels = expression(T[0] ~ tilde("") ~ Exp(0.2), T[1] ~ tilde("") ~ Exp(0.1))
  ) +
  # Indicator line for RMST cutoff
  geom_vline(
    xintercept = 10, linewidth = 0.9,
    linetype = "longdash", color = "#222222"
  ) +
  # Fine-tuning of axes
  scale_x_continuous(
    breaks = seq(0, 10, by = 2.5),
    limits = c(0, 10.5),
    expand = expansion(mult = c(0, 0), add = c(0.5, 0))
  ) +
  scale_y_continuous(limits = 0:1) +
  # Axes labels
  labs(x = "\nTime", y = "Survival probability\n")


# Combine plots ----

p2 = p2 +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )

wrap_plots(p1, p2, ncol = 2) +
  plot_layout(axis_titles = "collect", guides = "collect") &
  theme(legend.position = "top")
```

Now, the question remains how to estimate $\mu(t^*)$ for an observed data set.
Broadly, a point estimator for $\mu(t^*)$ can be obtained by integrating an estimator of the survival function:
$$
\muhat(t^*) = \int_0^{t^*} \hat{S}(u) \, du
$$
In principle, any estimator $\hat{S}$ can be applied but most commonly the non-parametric Kaplan-Meier estimator [@kaplan1958] is used.
The reasons for this are twofold.
On the one hand, using a non-parametric estimator avoids making any possibly false assumptions about the shape of the survival curve.
On the other hand, using this estimator closed-form solutions for both, the point and the variance estimator, are available and there is no need to rely on computational methods like numerical integration or resampling.
Concretely, the point estimator utilizing the Kaplan-Meier estimator of the survival function is given by
$$
\muhat(t^*) = \sum_{j=0}^D (t_{j+1} - t_j) \hat{S}(t_j) \, ,
$$ {#eq-pointest}
where $t_1 < t_2 < \ldots < t_D$ denote the ordered and distinct event times observed in the survival data and $t_{D+1} = t^*$.
Moreover, let $Y_j$ denote the number of individuals at risk just prior to $t_j$ and $d_j$ the number of events at $t_j$.
An estimator for the variance of (@eq-pointest) based on Greenwood's formula is then given by
$$
\Varhat[\muhat(t^*)] = \sum_{j=1}^D 
\left[ \sum_{i=j}^D (t_{i+1} - t_i) \hat{S}(t_i) \right]^2
\frac{d_j}{Y_j (Y_j - d_j)}
\, .
$$ {#eq-varest1}
Alternatively, the variance can be estimated by
$$
\Varhat[\muhat(t^*)] = \sum_{j=1}^D 
\left[ \sum_{i=j}^D (t_{i+1} - t_i) \hat{S}(t_i) \right]^2
\frac{d_j}{Y_j^2}
\, ,
$${#eq-varest2}
which is derived by plugging in the Nelson-Aalen estimator of the cumulative hazard rate into the theoretical variance formula [@ditzhaus2023].
Both variance estimators are valid but since most authors employ the estimator (@eq-varest1) we use it here per default as well.
