---
bibliography: ["../bib/references.bib", "../bib/packages.bib"]
---

# Conclusions {#sec-conclusion}

This thesis dealt with conducting statistical inference to compare two groups with a time-to-event endpoint under non-proportional hazards.
We further focused on procedures for which the effect measure and the statistical test are aligned with each other.
This led us to an assessment of the restricted mean survival time (RMST) as a population-level summary measure.
We reviewed the literature about corresponding methods for estimating and testing such effects and found that the standard asymptotic test based on a standard normal approximation suffers from an inflated type I error rate in finite sample settings.
While there exist a couple of proposed methods dealing with this problem we focused on the studentized permutation test by @ditzhaus2023 since these authors demonstrated it to be superior to the competing approaches overall.
In addition, we proposed two further methods for such scenarios based on pseudo-observations regression models.
The first of these two approaches also uses an asymptotic test but the estimation of the standard error of the effect estimate is carried out differently.
Here, the HC3 covariance matrix estimator is used, which we believed to be more robust in settings with rather small sample sizes based on results from previous research.
Furthermore, we implemented a nonparametric bootstrap test for such regression models such that we would have an additional method that does not make a fixed assumption about the (asymptotic) distribution of the test statistic used for testing the effect.
For this approach, we encountered the computational challenge of dealing with a nested resampling procedure with the calculation of the pseudo-observations on the first level and the bootstrap procedure on the second level.
We have addressed this problem by replacing the usage of ordinary pseudo-observations with infinitesimal jackknife pseudo-observations, which can be computed much faster.
After introducing the existing and our proposed approaches we set up a simulation study for empirically investigating and comparing them to each other.
For this, we adapted certain characteristics from the simulation study by @ditzhaus2023, making the simulation study less subjective.
Finally, we illustrated the application of all methods on empirical data sets from past clinical trials.

In summary, this thesis delivered two main contributions to existing research.
On the one hand, we validated the results by @ditzhaus2023 regarding their proposed studentized permutation method for two-sample RMST-based tests, i.e. we could confirm that its operating characteristics are better than those of the standard asymptotic approach in a vast majority of different scenarios.
On the other hand, we extended the repertoire of statistical methods for such tests for scenarios with moderate sample sizes by the two proposed methods based on pseudo-observations.
For these, we could show that they provide further valid alternatives that should be preferred over the standard asymptotic test.
The performance of both methods was only slightly inferior, overall, to that of the studentized permutation test.
For the asymptotic pseudo-observations method this was due to a slightly too liberal behavior in settings with very small sample sizes, whereas the bootstrap approach was a little too conservative in these scenarios.
@ditzhaus2023 mention that their studentized permutation method can directly be extended to other settings in survival analysis, e.g. to situations with competing risks where multiple causes for the event of interest must be considered and accounted for.
They also refer to related summary measures such as window mean survival time [@paukner2021].
The same arguments apply to the pseudo-observations methods presented in this thesis and their implementation might even be considered more straightforward as existing software solutions can be applied directly.

Casting estimation and testing problems for the RMST into the framework of generalized linear models makes the pseudo-observations approaches attractive alternatives that should be considered further, both by practitioners and by methodological researchers in statistics.
The most interesting feature of the pseudo-observations methods can be considered the ease of incorporating prognostic covariates into the analysis, which can increase the precision and power of the effect estimate and the statistical test, respectively.
The demonstration on real-world data sets in @sec-examples already gave a flavor to this idea.
While for the pseudo-observations methods, we simply need to add the corresponding covariates into the regression model, the other approaches considered in this thesis would need to be modified, e.g. by means of stratification.
However, even if we implemented such modifications to the other methods, we still might expect them to be less effective in taking advantage of the adjustment for covariates than the pseudo-observations approaches.
For instance, taking a continuous covariate into account, using the pseudo-observations methods we can make full use of this information by simply incorporating it into the regression model.
Using an approach based on stratification, on the other hand, would require us to more or less arbitrarily divide the continuous variable into discrete categories.
Especially for situations with small sample sizes as considered in this thesis, this might lead to small subgroups and therefore imprecise and volatile effect estimates.
These ideas could further be investigated and systematically evaluated by means of simulation studies in future research.
Moreover, it would be interesting to see, whether covariate adjustment can diminish the conservativeness of the bootstrap method proposed in this thesis.
One particular challenge in conducting such a simulation study would consist of setting up proper models for simulating survival data conditional on other covariates than the treatment indicator for a given RMST difference $\Delta$.
Other aspects and questions arising from these ideas are, for instance, the effects of incorporating non-prognostic covariates into the analysis or the misspecification of the functional form of an effect.

Another aspect that could be studied further is the application of other resampling procedures for pseudo-observations regression models as alternatives to the nonparametric bootstrap presented in this thesis.
While the nonparametric bootstrap makes only few assumptions and is straightforward to implement, alternative resampling schemes may exhibit a better performance.
One particular method we think of is the wild bootstrap [@liu1988].
Intuitively, we think that such an approach can also work for pseudo-observations regression models.
However, theoretical considerations need to be made in this context.
First, we need to keep in mind that we employ quasi-likelihood methods and therefore need to figure out which resampling methods are valid for these types of models.
Second, it is not clear in how far the usage of pseudo-observations alters or complicates things as opposed to situations in which the response vector is fully observed and used as-is.
Besides potential improvements in terms of operating characteristics, what makes these ideas interesting is that they would be computationally much more efficient than the bootstrap procedure proposed in this thesis as we would avoid recalculating the pseudo-observations in each bootstrap iteration.

Lastly, we note that @munko2024 consider extensions of RMST-based tests to settings with more than two populations.
They investigate how to conduct a test for the global null hypothesis of equal RMSTs across all groups as well as carrying out multiple contrast tests for the pairwise RMST differences.
Similarly, the pseudo-observations approaches proposed in this thesis might be used and investigated for such problems.
