---
#keep-tex: true
latex-min-runs: 2
latex-max-runs: 4
format:
  pdf:
    template-partials:
      - tex/biblio.tex
    pdf-engine: pdflatex
    toc: false
    toc-depth: 3
    number-sections: true
    toccolor: black
    citecolor: blue
    linkcolor: black
    fig-pos: "htbp"
    documentclass: scrartcl
    classoption: [headings=normal, numbers=noenddot]
    fontsize: 12pt
    geometry:
      - left=2.5cm
      - right=2.5cm
      - top=2.5cm
      - bottom=2cm
      - bindingoffset=5mm
    cite-method: biblatex
    biblatexoptions:
      - backend=biber
      - maxbibnames=999
      - maxcitenames=2
      - uniquename=false
      - uniquelist=false
      - dashed=false
      - isbn=false
      - doi=false
      - eprint=false
      - url=false
      - date=year
    biblio-style: authoryear-icomp
    include-in-header: ["tex/preamble.tex", "tex/operators.tex"]
    include-before-body: ["tex/before_body.tex", "tex/abbreviations.tex"]
bibliography: ["bib/references.bib", "bib/packages.bib"]
execute: 
  echo: false
  warning: false
  output: true
crossref: 
  eq-prefix: "Eq."
suppress-bibliography: true
---

```{r setup}
box::use(
  here[here]
)

setwd(here())
options(box.path = here("R"))

# Include child documents
chapter = function(name) {
  here("thesis", "chapters", paste0(name, ".qmd"))
}

# Load modules and functions
box::use(
  data.table[...],
  data.table.extras[setj_at],
  # plotting
  ggplot2[...],
  patchwork[wrap_plots, plot_layout],
  ggsurvfit[survfit2, ggsurvfit, add_censor_mark],
  # tables
  kableExtra[...],
  # survival
  survival[Surv, survfit, survdiff, coxph, cox_zph = cox.zph],
  eventglm[rmeanglm],
  flexsurv[flexsurvspline],
  # misc
  withr[with_seed],
  fs
)

box::use(
  # plotting
  plotting/surv[plot_surv_models],
  plotting/cens[plot_cens_models],
  # simulation results
  simfuns2/analyze[calc_rejection_rates, calc_ci_metrics, setj_samples_alloc, setj_percent],
  simfuns2/get_funs[get_scenario_table],
  # RMST methods
  rmst/km[rmst_diff_test, rmst_diff_studperm],
  rmst/pseudo[pseudo_strat, pseudo_infjack, rmst_pseudo_test, rmst_pseudo_boot_test]
)

# Set (default) ggplot2 theme for entire document
theme_set(theme_bw(base_size = 16))

# Load simulation results
dtr = readRDS(here("simulation", "results", "2024-02-08_results1.rds"))
setDT(dtr)
dts = get_scenario_table()

# Function for formatting p-values in tables
format_pval = function(x) {
  fifelse(
    x < 0.1, "<0.1",
    format(round(x, 1), digits = 2, nsmall = 1)
  )
}
```


\newpage
\pagenumbering{arabic}

```{r child=chapter("01-introduction")}

```

```{r child=chapter("02-survnph")}

```

```{r child=chapter("03-inference")}

```

```{r child=chapter("04-simulation")}

```

```{r child=chapter("05-examples")}

```

```{r child=chapter("06-conclusion")}

```

\newpage

# References {-}

\begingroup
<!-- Increase space between bibliography entries -->
\setlength\bibitemsep{0.5\baselineskip}
<!-- Bibliography -->
\printbibliography[heading=none]
\endgroup
\def\printbibliography{}

\newpage
\appendix

```{r child=chapter("99-appendix")}

```

\newpage
\thispagestyle{empty}

```{r child=chapter("99-affidavit")}

```

